### PR TITLE
Boilerplate

### PR DESCRIPTION
**Pull request by binilj04**
This is a boilerplate code to make a discord bot. 
Uses the **discord.js** library. 
The bot was tested and  works with:

- npm version: 3.10.10

- node: 6.12.3

### CODE REVIEW

**Comment by adilanchian** [comment]
BTW I should probably setup a better way to show what should be changed haha. Thanks again!

**Comment by splinterific** [comment]
you will need to update `package.json` on line 8 to `"start": "node index.js"` if you've removed `server.js` @binilj04 👍

**Comment by binilj04** [comment]
Thanks @adilanchian  and @splinterific . I hope i understood the  config.json correct, if  there is addition to the config.json, one needs to commit changes to config.json without it being in the gitignore and then adding the file in the gitignore in the next commit.

**Comment by binilj04** [comment]
Used dotenv library to read BOT_KEY from environment variable (.env).

**Comment by adilanchian** [comment]
Noice work @binilj04 ! I went ahead and merged this in! GOing to go ahead and remove this branch :)

**Pull request merged**
